# Generated by Django 4.1.3 on 2024-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpartyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
